ARG NODE_VERSION=22-alpine
FROM node:${NODE_VERSION} AS node

FROM php:8.4-apache AS php
WORKDIR /var/www/html
ARG UID
ARG GID

# Hunspell doesn't work without a proper locale :o
RUN apt-get update && \
    apt-get install -y \
    curl sudo git gh nano python3

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

# Add extensions not included in the base image
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/download/2.7.24/install-php-extensions /usr/local/bin/
RUN install-php-extensions gd gmp memcached pdo_pgsql pdo_mysql xdebug zip pcntl bcmath intl
COPY docker/sites-available/000-default.conf.dev /etc/apache2/sites-available/000-default.conf

RUN echo "xdebug.mode=debug,develop,profile" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.start_with_request=trigger" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.trigger_value=profile_me" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.output_dir=/tmp/xdebug-profiles" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.profiler_output_name=cachegrind.out.%p.%t" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && mkdir -p /tmp/xdebug-profiles && chmod 777 /tmp/xdebug-profiles

RUN a2enmod rewrite headers

RUN addgroup --gid $GID laravel && \
    adduser --uid $UID --gid $GID --disabled-password --gecos "" laravel && \
    echo 'laravel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN chown -R laravel:laravel .

USER laravel

ENV NVM_DIR /home/laravel/.nvm
ENV PATH "/home/laravel/.local/bin:${PATH}"

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install 22 \
    && nvm use 22 \
    && curl -fsSL https://claude.ai/install.sh | bash
