name: creshu-prod

services:
  traefik:
    image: traefik:v3.3
    mem_limit: 160m
    env_file:
      - path: ./.env.prod      
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=postmaster@cantores.hu
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik
  migrator:
    image: creshu-app-prod
    user: "33:33" # www-data
    mem_limit: 256m
    env_file:
      - path: ./.env.prod
        required: false
    volumes:
      - storage:/var/www/html/storage
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal
    entrypoint: []
    command: ["/bin/sh", "-c", "php artisan migrate -n --force && php artisan optimize"]
    restart: "no"
  app:
    image: creshu-app-prod
    mem_limit: 768m
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - GIT_COMMIT_HASH=${GIT_COMMIT_HASH:-}
    # Use this when building: GIT_COMMIT_HASH=$(git rev-parse HEAD) docker compose ...
    env_file:
      - path: ./.env.prod # write your customizations here - these are used as environment variables, not from the file inside the container
        required: false
    volumes:
      - storage:/var/www/html/storage
      - ./import:/var/www/html/import:ro
    depends_on:
      database:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    labels:
      - traefik.enable=true
      - traefik.docker.network=creshu-prod_traefik
      - traefik.http.routers.myapp.rule=Host(`${APP_DOMAIN}`) || Host(`www.${APP_DOMAIN}`)
      - traefik.http.services.myapp.loadbalancer.server.port=80
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.mywwwredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.myapp.middlewares=mywwwredirect,hsts,compress
      - traefik.http.routers.myapp.priority=10
      - traefik.http.middlewares.compress.compress=true
      - traefik.http.middlewares.hsts.headers.stsSeconds=31536000
      - traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.hsts.headers.stsPreload=true      
    networks:
      - traefik
      - internal
  database:
    image: pgvector/pgvector:pg17
    mem_limit: 512m
    env_file:
      - ./.env.prod # for the database credentials
    networks:
      - internal
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cantor -d cantores"]
      start_period: 1m
      interval: 10s
      timeout: 5s
      retries: 3      
  memcached:
    image: memcached:1.6
    mem_limit: 128m
    command:
      - --memory-limit=96
    networks:
      - internal
volumes:
  db-data:
  storage:
  letsencrypt:
networks:
  traefik:
  internal:
